default:
  role: "GRP_AZ_DA_PROD_ELECTRICITY_ANALYST"
  db: "DATAANALYTICS_DB_PRD"
  wh: "DAP_WH_PROD_ELECTRICITY"

prod_analyst:
  role: "GRP_AZ_DA_PROD_ELECTRICITY_ANALYST"
  db: "DATAANALYTICS_DB_PRD"
  wh: "DAP_WH_PROD_ELECTRICITY"

nonprod_analyst:
  role: "GRP_AZ_DA_NONPROD_ELECTRICITY_ANALYST"
  db: "DATAANALYTICS_DB_TST"
  wh: "DAP_WH_NONPROD_ELECTRICITY"